### ISSUE TITLE
Failed to obtain get_unsolved_python_packages_versions_change - fails to authenticate

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#249]
From stage environment:

```
2019-12-18 13:21:27,178 [26] ERROR    thoth.metrics_exporter:91: Failed to run metrics gathering job SolverMetrics.get_unsolved_python_packages_versions_change
--
  | Traceback (most recent call last):
  | File "/opt/app-root/src/wsgi.py", line 89, in func_wrapper
  | job()
  | File "</opt/app-root/lib/python3.6/site-packages/decorator.py:decorator-gen-27>", line 2, in get_unsolved_python_packages_versions_change
  | File "/opt/app-root/src/thoth/metrics_exporter/jobs/base.py", line 41, in register_metric_job
  | method(*args, **kwargs)
  | File "/opt/app-root/src/thoth/metrics_exporter/jobs/solver.py", line 87, in get_unsolved_python_packages_versions_change
  | 'instance': f"metrics-exporter-{cls._NAMESPACE}.cloud.paas.psi.redhat.com:80"}
  | File "/opt/app-root/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
  | return Retrying(*dargs, **dkw).call(f, *args, **kw)
  | File "/opt/app-root/lib/python3.6/site-packages/retrying.py", line 212, in call
  | raise attempt.get()
  | File "/opt/app-root/lib/python3.6/site-packages/retrying.py", line 247, in get
  | six.reraise(self.value[0], self.value[1], self.value[2])
  | File "/opt/app-root/lib/python3.6/site-packages/six.py", line 696, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/retrying.py", line 200, in call
  | attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  | File "/opt/app-root/lib/python3.6/site-packages/prometheus_api_client/prometheus_connect.py", line 111, in get_current_metric_value
  | "HTTP Status Code {} ({})".format(response.status_code, response.content)
  | Exception: HTTP Status Code 403 (b'\n<!DOCTYPE html>...

```

**Comment by fridex** [comment]
Duplicate #253
