### ISSUE TITLE
readiness probe to check for db schema up to date?

### ISSUE THREAD

**Issue by goern** [thoth-station/metrics-exporter#403]
**Is your feature request related to a problem? Please describe.**
metrics-exporter starts up and gets into ready state, even if the process throws a lot of errors due to the fact that the database is not initialized.

```
2020-06-09 06:28:41,349  26 ERROR    thoth.metrics_exporter:89: Failed to run metrics gathering job DBMetrics.get_tot_main_records_count
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "python_package_requirement" does not exist
LINE 2: FROM python_package_requirement
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/src/wsgi.py", line 87, in func_wrapper
    job()
  File "<decorator-gen-11>", line 2, in get_tot_main_records_count
  File "/opt/app-root/src/thoth/metrics_exporter/jobs/base.py", line 41, in register_metric_job
    method(*args, **kwargs)
  File "/opt/app-root/src/thoth/metrics_exporter/jobs/db.py", line 78, in get_tot_main_records_count
    main_models_records = cls.graph().get_main_table_count()
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 5134, in get_main_table_count
    result[main_model.__tablename__] = session.query(func.count(main_model.id)).scalar()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3393, in scalar
    ret = self.one()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3360, in one
    ret = self.one_or_none()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3329, in one_or_none
    ret = list(self)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3405, in __iter__
    return self._execute_and_instances(context)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3430, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "python_package_requirement" does not exist
LINE 2: FROM python_package_requirement
             ^

[SQL: SELECT count(python_package_requirement.id) AS count_1 
FROM python_package_requirement]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Describe the solution you'd like**
Let's have a readiness probe that takes db schema into account

**Describe alternatives you've considered**
better exception handling within metrics-exporter.

**Additional context**
n/a

**Comment by fridex** [comment]
This looks like `THOTH_METRICS_EXPORTER_WEAK_READINESS` is set to 1. In that case, there is no guarantee the metrics are available.

**Comment by pacospace** [comment]
> This looks like `THOTH_METRICS_EXPORTER_WEAK_READINESS` is set to 1. In that case, there is no guarantee the metrics are available.

Yes exactly, and that is because metrics-exporter never gets ready in stage at least, even with 30 minutes and the problem is the evaluation of SLI in stage which takes lot of time. I'll look into that

**Comment by fridex** [comment]
Do we want to mark just some of the metrics to be scraped to become ready and omit the other ones?

Back in the days, I tried forcing metrics-exporter to aggregate all the matrics so we do not see "gaps" in the aggregated data. For some metrics it might be ok-ish.

**Comment by pacospace** [comment]
https://github.com/thoth-station/metrics-exporter/pull/405

**Comment by goern** [comment]
feels to me like this can be closed?! syn?
