### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by pacospace** [thoth-station/metrics-exporter#84]
metrics-exporter is not able to evaluate metrics from several namespace.
```

2019-07-22 09:52:41,504 [33] ERROR    apscheduler.executors.default:131: Job "get_configmaps_per_namespace_per_label (trigger: interval[0:00:20], next run at: 2019-07-22 09:53:01 UTC)" raised an exception
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 41, in inner
  | resp = func(self, resource, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 168, in get
  | return self.request('get', path, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 309, in request
  | _return_http_data_only=params.get('_return_http_data_only', True)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
  | _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
  | _request_timeout=_request_timeout)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
  | headers=headers)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
  | query_params=query_params)
  | File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
  | raise ApiException(http_resp=r)
  | kubernetes.client.rest.ApiException: (403)
  | Reason: Forbidden
  | HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 22 Jul 2019 09:52:41 GMT', 'Content-Length': '321'})
  | HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \\"system:serviceaccount:thoth-frontend-stage:thoth-ops\\" cannot list configmaps in the namespace \\"thoth-amun-api-stage\\": no RBAC policy matched","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}\n'

```

**Comment by fridex** [comment]
This has been already fixed. Closing.
